AWSTemplateFormatVersion: 2010-09-09
Description: >-
  SAM-Gist

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs16.x
    CodeUri: src
    Timeout: 30

Resources:
  ServerlessApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        ApiKeyRequired: false
        DefaultAuthorizer: None

  GetAlbumUrlsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Events:
        GetAlbumUrlsResource:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApi
            Path: /
            Method: post